# Generated by Django 5.2 on 2025-04-10 15:46

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('django', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='paytechuz_t_account_ec3b6c_idx',
            old_name='paytechuz_t_account_e6a0f0_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='paytechuz_t_state_e19505_idx',
            old_name='paytechuz_t_state_6c8d8e_idx',
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='account_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='state',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Initiating'), (2, 'Successfully'), (-2, 'Cancelled after successful performed'), (-1, 'Cancelled during initiation')], default=0),
        ),
    ]
