import os
import pathlib
import shutil
from setuptools import setup, find_packages, Extension
from Cython.Build import cythonize

# Configuration
SOURCE_DIR = "src"
PACKAGE_NAME = "paytechuz"

def get_extensions():
    extensions = []
    # Walk through the src directory to find all .py files
    for root, _, files in os.walk(os.path.join(SOURCE_DIR, PACKAGE_NAME)):
        if "migrations" in root.split(os.path.sep):
            continue
            
        for file in files:
            if file.endswith(".py"):
                path = os.path.join(root, file)
                
                # Skip __init__.py and client.py files from compilation
                # client.py files remain as pure Python for better IDE support
                # but delegate to compiled internal.py files
                if file in ["__init__.py", "client.py"]:
                    continue
                
                rel_path = os.path.relpath(path, SOURCE_DIR)
                module_name = rel_path.replace(os.path.sep, ".")[:-3]
                
                extensions.append(Extension(module_name, [path]))
    return extensions

def delete_source_files():
    print("🧹 Cleaning up source .py files...")
    for root, _, files in os.walk(os.path.join(SOURCE_DIR, PACKAGE_NAME)):
        if "migrations" in root.split(os.path.sep):
            continue
            
        for file in files:
            # Skip __init__.py and client.py files
            if file.endswith(".py") and file not in ["__init__.py", "client.py"]:
                file_path = os.path.join(root, file)
                print(f"   Removing {file_path}")
                os.remove(file_path)
    
    # Also remove .c files generated by Cython
    for root, _, files in os.walk(os.path.join(SOURCE_DIR, PACKAGE_NAME)):
        for file in files:
            if file.endswith(".c"):
                file_path = os.path.join(root, file)
                os.remove(file_path)

if __name__ == "__main__":
    # 1. Compile
    print("🚀 Starting Cython build...")
    setup(
        ext_modules=cythonize(
            get_extensions(),
            compiler_directives={'language_level': "3", 'always_allow_keywords': True},
            build_dir="build"
        ),
        script_args=["build_ext", "--inplace"]
    )
    
    # 2. Cleanup .py files to leave only .so files
    delete_source_files()
    print("✅ Cython build and cleanup complete.")
